name: Security Scanners

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/sast-action@1.3.0
        with:
          scan_config_path: .github/sast-config.yaml

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/sca-action@1.2.0
        with:
          scan_config_path: .github/sca-config.yaml

  ss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/ss-action@0.2.0
        with:
          scan_config_path: .github/ss-config.yaml